name: MuhaMind Frontend CI

on:
    push:
        branches: [main, develop]
        paths-ignore:
            - "README.md"
            - "docs/**"
    pull_request:
        branches: [main, develop]
        paths-ignore:
            - "README.md"
            - "docs/**"

jobs:
    frontend:
        name: Frontend CI
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./frontend

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run one test
              run: npm test -- --testPathPattern=some-test-file
